version = 1

test_patterns = ["test/**"]

exclude_patterns = ["README.md"]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "test-coverage"
enabled = true

[[transformers]]
name = "black"
enabled = true

