name: reconstructSPI
channels:
  - conda-forge
  - defaults
dependencies:
  - codecov
  - coverage
  - gemmi
  - numpy
  - pillow>=8.2.0
  - pip
  - pytest
  - pytest-cov
  - pytorch
  - scipy
  - pip :
      - git+https://github.com/compSPI/simSPI.git
      - git+https://github.com/compSPI/compSPI.git
      - geomstats
