name: reconstructSPI
channels:
  - conda-forge
  - defaults
dependencies:
  - codecov
  - coverage
  - gemmi
  - numba
  - numpy
  - pillow>=8.2.0
  - pip
  - pytest
  - pytest-cov
  - pytorch
  - pip :
      - git+https://github.com/compSPI/reconstructSPI.git

